### ISSUE TITLE
Port to Osg

### ISSUE THREAD

**Issue by otse** [scanberg/hbao#1]
Hi,

Porting this to Osg wasn't a big deal at all. No mat4 uniforms or anything... I thought you just never finished it...

For the 4 × 4 noise texture, I used standard `rand() % 255`, but it looks a bit too even. Does the radial random look better?

![nw_2018-08-26_22-11-18](https://user-images.githubusercontent.com/1123362/44632849-6202e680-a982-11e8-8a7b-5b1947dbadf6.jpg)

**Comment by scanberg** [comment]
First of all: Sorry for the incredibly late reply.

This project is dead in the water and very old. There are a lot of things I would change today, and there have been several improvements to SSAO techniques overall over this technique.

The distribution within the noise texture is not incredibly important as it is rotated and permuted within the shader and most importantly it is meant to be low-pass filtered with the blur pass which removes the high-frequency patterns clearly visible.

Best
Robin
